### ISSUE TITLE
Missing top level 'services:' in docker-compose.yml

### ISSUE THREAD

**Issue by martinacat** [spring-cloud-samples/configserver#34]
`docker-compose up` doesn't work as the compose file is missing the top level `services:` 

correct syntax:
```
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
```
